name: DevOps Dashboard CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Frontend
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Install Backend
        run: |
          cd backend
          npm install

      - name: Check Backend
        run: |
          cd backend
          node -v

      - name: Success Message
        run: echo "Pipeline Success"
